import { Body, Controller, Get, Param, Patch, Post, Query, Req, UseGuards } from '@nestjs/common';
import { PrismaService } from '../prisma.service'; import { AuthGuard } from '../common/auth.guard'; import { Permission } from '../common/decorators'; import { PermissionGuard } from '../common/permission.guard'; import { AuditService } from '../audit.service';
@Controller('customers') @UseGuards(AuthGuard,PermissionGuard)
export class CustomersController { constructor(private prisma:PrismaService,private audit:AuditService){}
 @Get() @Permission('CUSTOMER.VIEW') list(@Query('search')search?:string){return this.prisma.customer.findMany({where:search?{OR:[{name:{contains:search,mode:'insensitive'}},{companyName:{contains:search,mode:'insensitive'}},{contactPerson:{contains:search,mode:'insensitive'}}]}:undefined,include:{category:true},orderBy:{name:'asc'}})}
 @Post() @Permission('CUSTOMER.MANAGE') async create(@Body()body:any,@Req()req:any){const c=await this.prisma.customer.create({data:{name:body.name,companyName:body.companyName,contactPerson:body.contactPerson,phone:body.phone,email:body.email,address:body.address,latitude:body.latitude,longitude:body.longitude,geofenceRadius:body.geofenceRadius||100,contractStart:body.contractStart?new Date(body.contractStart):null,contractEnd:body.contractEnd?new Date(body.contractEnd):null,status:body.status!==false}});await this.audit.log(req.user.sub,'CUSTOMER_CREATED','CUSTOMERS',c.id,null,c,req);return c}
 @Patch(':id') @Permission('CUSTOMER.MANAGE') async patch(@Param('id')id:string,@Body()body:any,@Req()req:any){const old=await this.prisma.customer.findUnique({where:{id}});const c=await this.prisma.customer.update({where:{id},data:{...body,contractStart:body.contractStart?new Date(body.contractStart):undefined,contractEnd:body.contractEnd?new Date(body.contractEnd):undefined}});await this.audit.log(req.user.sub,'CUSTOMER_UPDATED','CUSTOMERS',id,old,c,req);return c}
 @Get(':id') @Permission('CUSTOMER.VIEW') get(@Param('id')id:string){return this.prisma.customer.findUnique({where:{id},include:{category:true,tasks:true,serviceReports:true}})}
}
