import { Body, Controller, Get, Post, Query, Req, UseGuards } from '@nestjs/common';
import { PrismaService } from '../prisma.service'; import { AuthGuard } from '../common/auth.guard'; import { Permission } from '../common/decorators'; import { PermissionGuard } from '../common/permission.guard';
@Controller('location') @UseGuards(AuthGuard,PermissionGuard)
export class LocationController { constructor(private prisma:PrismaService){}
 @Post('heartbeat') @Permission('LOCATION.VIEW') async heartbeat(@Body()b:any,@Req()req:any){const now=new Date();await this.prisma.user.update({where:{id:req.user.sub},data:{lastSeenAt:now,lastLatitude:b.latitude,lastLongitude:b.longitude,lastAccuracy:b.accuracy}});if(b.latitude&&b.longitude)await this.prisma.gpsPoint.create({data:{userId:req.user.sub,taskId:b.taskId||null,latitude:b.latitude,longitude:b.longitude,accuracy:b.accuracy,speed:b.speed,heading:b.heading,timestamp:now,deviceId:b.deviceId}});return {ok:true,timestamp:now};}
 @Post('batch') @Permission('LOCATION.VIEW') async batch(@Body()b:any,@Req()req:any){const points=b.points||[];if(!points.length)return {ok:true,count:0};await this.prisma.$transaction(points.map((p:any)=>this.prisma.gpsPoint.create({data:{userId:req.user.sub,taskId:p.taskId||null,latitude:p.latitude,longitude:p.longitude,accuracy:p.accuracy,speed:p.speed,heading:p.heading,timestamp:new Date(p.timestamp||Date.now()),deviceId:p.deviceId}})));const last=points[points.length-1];await this.prisma.user.update({where:{id:req.user.sub},data:{lastSeenAt:new Date(),lastLatitude:last.latitude,lastLongitude:last.longitude,lastAccuracy:last.accuracy}});return {ok:true,count:points.length};}
 @Get('current') @Permission('LOCATION.TRACK') current(){return this.prisma.user.findMany({where:{status:'ACTIVE'},select:{id:true,fullName:true,username:true,position:true,lastSeenAt:true,lastLatitude:true,lastLongitude:true,lastAccuracy:true}})}
 @Get('history') @Permission('LOCATION.TRACK') history(@Query('userId')userId?:string,@Query('from')from?:string,@Query('to')to?:string){return this.prisma.gpsPoint.findMany({where:{userId,timestamp:{gte:from?new Date(from):undefined,lte:to?new Date(to):undefined}},orderBy:{timestamp:'asc'},take:10000})}
}
