import { Body, Controller, Get, Param, Patch, Post, Req, UseGuards } from '@nestjs/common';
import { PrismaService } from '../prisma.service'; import { AuthGuard } from '../common/auth.guard'; import { Permission } from '../common/decorators'; import { PermissionGuard } from '../common/permission.guard'; import { AuditService } from '../audit.service';
@Controller('tasks') @UseGuards(AuthGuard,PermissionGuard)
export class TasksController { constructor(private prisma:PrismaService,private audit:AuditService){}
 @Get() @Permission('TASK.VIEW') list(@Req()req:any){const isAdmin=req.user.role==='Admin';return this.prisma.task.findMany({where:isAdmin?undefined:{assignments:{some:{userId:req.user.sub}}},include:{customer:true,assignments:{include:{user:{select:{id:true,fullName:true,username:true}}}},serviceReport:true},orderBy:{createdAt:'desc'}})}
 @Post() @Permission('TASK.CREATE') async create(@Body()b:any,@Req()req:any){const task=await this.prisma.task.create({data:{taskCode:b.taskCode||`TASK-${Date.now()}`,customerId:b.customerId,title:b.title,workDescription:b.workDescription,serviceArea:b.serviceArea,scheduledStart:b.scheduledStart?new Date(b.scheduledStart):null,deadline:b.deadline?new Date(b.deadline):null,status:b.status||'DRAFT',createdById:req.user.sub,assignments:{create:(b.technicianIds||[]).map((userId:string)=>({userId}))}}});await this.audit.log(req.user.sub,'TASK_CREATED','TASKS',task.id,null,task,req);return task}
 @Get(':id') @Permission('TASK.VIEW') get(@Param('id')id:string){return this.prisma.task.findUnique({where:{id},include:{customer:true,assignments:{include:{user:true}},attendance:true,gpsPoints:{orderBy:{timestamp:'desc'},take:100},serviceReport:{include:{findings:true,treatments:true,photos:true}}}})}
 @Patch(':id') @Permission('TASK.UPDATE') async patch(@Param('id')id:string,@Body()b:any,@Req()req:any){const old=await this.prisma.task.findUnique({where:{id}});const task=await this.prisma.task.update({where:{id},data:{title:b.title,workDescription:b.workDescription,serviceArea:b.serviceArea,scheduledStart:b.scheduledStart?new Date(b.scheduledStart):undefined,deadline:b.deadline?new Date(b.deadline):undefined,status:b.status}});await this.audit.log(req.user.sub,'TASK_UPDATED','TASKS',id,old,task,req);return task}
 @Post(':id/assign') @Permission('TASK.UPDATE') async assign(@Param('id')id:string,@Body()b:any,@Req()req:any){await this.prisma.taskAssignment.deleteMany({where:{taskId:id}});for(const userId of b.technicianIds||[])await this.prisma.taskAssignment.create({data:{taskId:id,userId}});const task=await this.prisma.task.update({where:{id},data:{status:'ASSIGNED'}});await this.audit.log(req.user.sub,'TASK_ASSIGNED','TASKS',id,null,b,req);return task}
}
